---
title: "p8105_hw6_td2809"
author: "Chris Deng"
date: "2023-11-30"
output: html_document
---
```{r}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(modelr)


# remove the frame and change legend to bottom
theme_set(theme_minimal() + theme(legend.position = "bottom"))  

# change continuous variables with "viridis" for color and fill 
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

# change discrete variables with "viridis" for color and fill 
scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```
# Problem 1
```{r}
homicide_data = read_csv("data/homicide-data.csv") |>
  janitor::clean_names() |>
  mutate(city_state = paste(city, state, sep = ", "),
         solved = as_factor(if_else(disposition %in% c("Closed without arrest", "Closed by arrest"), 1, 0)),
         victim_age = as.numeric(victim_age)) |>
  filter(!city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"),
         victim_race %in% c("White", "Black"))
baltimore_data = homicide_data %>%
  filter(city_state == "Baltimore, MD")
```

```{r}
baltimore_glm = glm(solved ~ victim_age + victim_sex + victim_race, family = binomial, data = baltimore_data)
baltimore_glm |> 
  broom::tidy() |> 
  mutate(
    conf_low = estimate - 1.96 * std.error,
    conf_high = estimate + 1.96 * std.error,
    OR = exp(estimate),
    OR_conf_low = exp(conf_low),
    OR_conf_high = exp(conf_high)
  ) |> 
  filter(term == "victim_sexMale") |> 
  select(term, starts_with("OR"))
```
The adjusted odds ratio is 0.415 and confidence interval is [0.318, 0.542].

Now, run `glm` for each of the cities in the dataset, and extract the adjusted odds ratio (and CI) for solving homicides comparing male victims to female victims.
```{r}

```

Create a plot that shows the estimated ORs and CIs for each city. 
